version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    # volumes:
    #   - ./client:/usr/src/app
  server:
    build: ./server
    ports:
      - "1338:1338"
    # volumes:
    #   - ./server:/usr/src/app